### ISSUE TITLE
Use organization package `rpc-handler` to get the fastest provider available

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquibot/command-wallet#3]
I had no luck when trying to use the rpc package so I want to do it in a separate PR. This endpoint was quite reliable during my tests which is why I kept it. You can even try it in my testing repo if you want.

_Originally posted by @gentlementlegen in https://github.com/ubiquibot/command-wallet/pull/2#discussion_r1663135402_
            

Depends on https://github.com/ubiquity/rpc-handler/pull/45 to be published.

**Comment by gentlementlegen** [comment]
The following issue would need to be resolved to avoid the bugs that I encountered: https://github.com/ubiquity/rpc-handler/issues/32

**Comment by gentlementlegen** [comment]
The main issue currently is that the `rpc-handler` package makes too many requests and triggers a cancellation on the worker. There should be an option to limit the amount of tested networks in the package.

**Comment by gentlementlegen** [comment]
Update: I've been working all day on this, by changing the `rpc-handler` package to either include only specified URLs or even hardcoding a list of URLs. Every time I get the following message:
```
"HttpError: Too many subrequests."
```

Maybe our package is not suited for this. In the end we do not care about having the fastest RPC but any that works. Maybe it would be best to simply use the same package we use in `rpc-handler`, and try them one by one until the first one that works to avoid bursting the request limit within the workers. @rndquu thoughts?

**Comment by gentlementlegen** [comment]
@rndquu That is correct.

**Comment by rndquu** [comment]
@gentlementlegen @Keyrxng 

So the issue is that https://github.com/ubiquity/rpc-handler can't be used in a cloudflare environment (at least for now) because of a great number of HTTP requests in the background.

Perhaps we should add a new method to https://github.com/ubiquity/rpc-handler like `handler.getAnyRpcProvider()` which would simply return the 1st item from https://chainlist.org/chain/1 without any background checks?

Update: I've just double checked and there's already an issue for that https://github.com/ubiquity/rpc-handler/issues/43 so it makes sense to put current issue on hold and implement https://github.com/ubiquity/rpc-handler/issues/43 first.

**Comment by Keyrxng** [comment]
Yeah I think we could create a generator function that tests the network RPCs one by one and we yield the first to pass with checks if possible or none if we still hit that error

@gentlementlegen have you tried passing a hex network id and manually assigning network and runtime rpcs? Hacky and might not work but I'm sure the `Networkish` type also includes hex but `rpc-handler` wouldn't find a list of networkd RPCs.

I quickly read through the code and I think that you always end up with all of the endpoints instead of just the custom ones you passed?

**Comment by gentlementlegen** [comment]
I was trying to solve the issue on the rpc package by skipping all the other endpoints but I didn't expect them to still count as network calls, even canceled or failed. A method to try them one by one seems to be a reliable idea, I will look into that.
